### PR TITLE
Add new property: servicePing

### PR DESCRIPTION
**Pull request by koalalam**

### CODE REVIEW

**Review by jplock — APPROVED** [review]

**Comment by koalalam** [comment]
@jplock, thank you very much. Can we cut a new version to include the recent changes?

**Comment by jplock** [comment]
Yes, working on it now, but waiting for something to update in Maven Central.

**Comment by jplock** [comment]
Nexus keeps rejecting my uploads tonight, so I'll try again later this week.  Sorry about that.

```
[INFO] [ERROR] Nexus Staging Rules Failure Report
[INFO] [ERROR] ==================================
[INFO] [ERROR] 
[INFO] [ERROR] Repository "comsmoketurner-1171" failures
[INFO] [ERROR]   Rule "checksum-staging" failures
[INFO] [ERROR]     * Missing SHA1: '/com/smoketurner/dropwizard/consul-ribbon/1.3.7-2/consul-ribbon-1.3.7-2-sources.jar.sha1'
```

It's just that one file and I've tried uploading the assets a few times now through `mvn release`

**Comment by koalalam** [comment]
@jplock , thank you very much. Would be great if a new version is ready by early next week.

**Comment by jplock** [comment]
same error tonight.  I haven't seen this before and I'm not quite sure how to fix it.  Other files, including the .asc files, are being uploaded fine.  Looks like the AWS SDK team is having issues too - https://issues.sonatype.org/browse/OSSRH-43364

**Comment by koalalam** [comment]
Is Maven version somehow related? as mentioned here: https://issues.sonatype.org/browse/OSSRH-43371?focusedCommentId=525725&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-525725

**Comment by jplock** [comment]
I've been using Maven 3.5.4 for a few months now and deployed things without issue.  It's just strange that its only that one .asc file and nothing else that is failing to upload.  That doesn't make any sense to me.

**Comment by koalalam** [comment]
I see. Could we raise a JIRA for this case?

**Comment by jplock** [comment]
I was able to publish two other modules I maintain to Nexus without issue.  I tried again with this project after removing the `Thread.sleep()` from the tests, but its still failing on the ribbon sources asc file not being present.  If you'd like to create a JIRA case, feel free.

**Comment by koalalam** [comment]
@jplock , raised one: https://issues.sonatype.org/browse/OSSRH-43697.  Please do provide more info that you think useful for troubleshooting

**Comment by koalalam** [comment]
@jplock, is there anything you/me can help address this issue? This is a shame we get code completed but couldn't use it.

**Comment by koalalam** [comment]
@jplock , "Can you drop that staging repository, try to re-deploy, and capture the full logs that you can attach here?" , would you be able give it a try?

**Comment by jplock** [comment]
@koalalam I just tired the deploy again and it worked 👍

**Pull request merged**
